project: 
  type: website
  output-dir: docs

website:
  title: "Madison L - Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/username/username.github.io
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Madison_L 2026©"
    right: 
      - icon: linkedin
        href: www.linkedin.com/in/madison-lindsay-2787982b7

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Data Analysis"
        file: analysis.qmd
      - text: "Data Exploration"
        file: exploration.qmd
      - text: "Programming"
        file: story_telling.qmd
      #- text: "Machine Learning"
        #file: ml.qmd
      - text: "Database Creation"
        file: full_stack.qmd
      #- text: "Competition"
       #file: competition.qmd
  
  # learn more about navication here https://quarto.org/docs/websites/website-navigation.html
  # comment out any of the sections below to turn off the sidebar

  sidebar: 
    - title: "Data Analysis"
      style: "docked"
      background: light
      contents:
        - text: "Data Analysis"
          file: analysis.qmd
        - text: "---"
        - text: "Rich Distributing"
          file: Analysis_Projects/Consulting.Rmd
        - text: "---"
        - text: "Music Education"
          file: Analysis_Projects/Semester_Project_Template.qmd
        - text: "---"
    - title: "Data Exploration"
      style: "docked"
      background: light
      contents:
        - text: "Data Exploration"
          file: exploration.qmd
        - text: "---"
        - text: "Is Reading Comprehension Declining?"
          file: Cleansing_Exploration/w13_task3.qmd
        - text: "---"
    - title: "Programming"
      style: "docked"
      background: light
      contents:
        - text: "Programming"
          file: story_telling.qmd
        - text: "---"
        - text: "College Fantasy Football"
          file: Story_Telling/college_fantasy_quarto.qmd
        - text: "---"
        - text: "Music Practice Room"
          file: Story_Telling/practice_room.qmd
        - text: "---"
    #- title: "Machine Learning"
      #style: "docked"
      #background: light
      #contents:
        #- text: "Machine Learning"
          #file: ml.qmd
        #- text: "---"
        #- text: "Project 1"
          #file: Machine_Learning/project1.qmd
        #- text: "---"
        #- text: "Project 2"
          #file: Machine_Learning/project2.qmd
        #- text: "---"
        #- text: "Project 3"
          #file: Machine_Learning/project3.qmd
        #- text: "---"
    - title: "Database Creation"
      style: "docked"
      background: light
      contents:
        - text: "Database Creation"
          file: full_stack.qmd
        - text: "---"
        - text: "Sheet Music Database"
          file: Full_Stack/sheet_music_db.qmd
        - text: "---"
    #- title: "Competition"
      #style: "docked"
      #background: light
      #contents:
        #- text: "Competition"
          #file: competition.qmd
        #- text: "---"
        #- text: "Project 1"
          #file: Competition/project1.qmd
        #- text: "---"
        #- text: "Project 2"
          #file: Competition/project2.qmd
        #- text: "---"
        #- text: "Project 3"
          #file: Competition/project3.qmd
        #- text: "---"

  
format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
    code-fold: true



